# Generated by Django 4.1 on 2024-03-02 13:46

import core.models.defaults
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_refreshtoken_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='system',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=models.JSONField(blank=True, default=core.models.defaults.default_location_data),
        ),
    ]
