#!/usr/bin/bash
# script installs python3-virtualenv
sudo apt update
sudo apt-get install build-essential libssl-dev libffi-dev python3-dev python2-dev python2 python-dev-is-python3 python3 python3-venv libpq-dev -y
sudo apt install python3-virtualenv -y
